# Form implementation generated from reading ui file 'UIWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 840)
        MainWindow.setMinimumSize(QtCore.QSize(1440, 840))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1421, 821))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.btnConnect = QtWidgets.QPushButton(parent=self.tab1)
        self.btnConnect.setGeometry(QtCore.QRect(240, 70, 111, 31))
        self.btnConnect.setObjectName("btnConnect")
        self.inputPort = QtWidgets.QLineEdit(parent=self.tab1)
        self.inputPort.setGeometry(QtCore.QRect(150, 75, 81, 21))
        self.inputPort.setObjectName("inputPort")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab1)
        self.groupBox_2.setGeometry(QtCore.QRect(130, 130, 401, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.label_17.setObjectName("label_17")
        self.btn_cancel_all_schedule = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btn_cancel_all_schedule.setGeometry(QtCore.QRect(140, 200, 113, 32))
        self.btn_cancel_all_schedule.setObjectName("btn_cancel_all_schedule")
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(20, 80, 61, 21))
        self.label_18.setObjectName("label_18")
        self.label_schedule_open_summary = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_schedule_open_summary.setGeometry(QtCore.QRect(90, 30, 291, 21))
        self.label_schedule_open_summary.setObjectName("label_schedule_open_summary")
        self.label_schedule_close_summary = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_schedule_close_summary.setGeometry(QtCore.QRect(90, 80, 291, 21))
        self.label_schedule_close_summary.setObjectName("label_schedule_close_summary")
        self.btn_get_all_schedule = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btn_get_all_schedule.setGeometry(QtCore.QRect(20, 200, 113, 32))
        self.btn_get_all_schedule.setObjectName("btn_get_all_schedule")
        self.label_schedule_close_summary_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_schedule_close_summary_2.setGeometry(QtCore.QRect(90, 130, 291, 21))
        self.label_schedule_close_summary_2.setObjectName("label_schedule_close_summary_2")
        self.label_19 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(20, 130, 61, 21))
        self.label_19.setObjectName("label_19")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = StrangleTab()
        self.tab2.setObjectName("tab2")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = PositionTab()
        self.tab3.setObjectName("tab3")
        self.tabWidget.addTab(self.tab3, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnConnect.setText(_translate("MainWindow", "链接客户端"))
        self.inputPort.setText(_translate("MainWindow", "7497"))
        self.groupBox_2.setTitle(_translate("MainWindow", "定时任务"))
        self.label_17.setText(_translate("MainWindow", "下单任务"))
        self.btn_cancel_all_schedule.setText(_translate("MainWindow", "取消所有任务"))
        self.label_18.setText(_translate("MainWindow", "定时平仓"))
        self.label_schedule_open_summary.setText(_translate("MainWindow", "无"))
        self.label_schedule_close_summary.setText(_translate("MainWindow", "无"))
        self.btn_get_all_schedule.setText(_translate("MainWindow", "查看任务"))
        self.label_schedule_close_summary_2.setText(_translate("MainWindow", "无"))
        self.label_19.setText(_translate("MainWindow", "盈利平仓"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "连接客户端"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "策略信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "平仓信息"))
from UIElements.PositionTab import PositionTab
from UIElements.StrangleTab import StrangleTab


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
