# Form implementation generated from reading ui file 'UIWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 840)
        MainWindow.setMinimumSize(QtCore.QSize(1440, 840))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1421, 821))
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideRight)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.btnConnect = QtWidgets.QPushButton(parent=self.tab1)
        self.btnConnect.setGeometry(QtCore.QRect(240, 70, 111, 31))
        self.btnConnect.setObjectName("btnConnect")
        self.inputPort = QtWidgets.QLineEdit(parent=self.tab1)
        self.inputPort.setGeometry(QtCore.QRect(150, 75, 81, 21))
        self.inputPort.setObjectName("inputPort")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.tab1)
        self.groupBox_2.setGeometry(QtCore.QRect(130, 130, 401, 261))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(20, 30, 61, 21))
        self.label_17.setObjectName("label_17")
        self.btn_cancel_all_schedule = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btn_cancel_all_schedule.setGeometry(QtCore.QRect(140, 200, 113, 32))
        self.btn_cancel_all_schedule.setObjectName("btn_cancel_all_schedule")
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(20, 80, 61, 21))
        self.label_18.setObjectName("label_18")
        self.label_schedule_open_summary = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_schedule_open_summary.setGeometry(QtCore.QRect(90, 30, 291, 21))
        self.label_schedule_open_summary.setObjectName("label_schedule_open_summary")
        self.label_schedule_close_summary = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_schedule_close_summary.setGeometry(QtCore.QRect(90, 80, 291, 21))
        self.label_schedule_close_summary.setObjectName("label_schedule_close_summary")
        self.btn_get_all_schedule = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btn_get_all_schedule.setGeometry(QtCore.QRect(20, 200, 113, 32))
        self.btn_get_all_schedule.setObjectName("btn_get_all_schedule")
        self.label_schedule_close_summary_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_schedule_close_summary_2.setGeometry(QtCore.QRect(90, 130, 291, 21))
        self.label_schedule_close_summary_2.setObjectName("label_schedule_close_summary_2")
        self.label_19 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(20, 130, 61, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.tab1)
        self.label_20.setGeometry(QtCore.QRect(380, 30, 61, 21))
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(parent=self.tab1)
        self.label_22.setGeometry(QtCore.QRect(420, 16, 91, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.tab1)
        self.label_23.setGeometry(QtCore.QRect(420, 46, 91, 21))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.tab1)
        self.label_24.setGeometry(QtCore.QRect(420, 110, 91, 21))
        self.label_24.setObjectName("label_24")
        self.label_21 = QtWidgets.QLabel(parent=self.tab1)
        self.label_21.setGeometry(QtCore.QRect(380, 94, 61, 21))
        self.label_21.setObjectName("label_21")
        self.label_25 = QtWidgets.QLabel(parent=self.tab1)
        self.label_25.setGeometry(QtCore.QRect(420, 80, 91, 21))
        self.label_25.setObjectName("label_25")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.tab1)
        self.textBrowser.setGeometry(QtCore.QRect(580, 60, 331, 81))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(parent=self.tab1)
        self.label.setGeometry(QtCore.QRect(710, 30, 60, 16))
        self.label.setObjectName("label")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.tab1)
        self.textBrowser_2.setGeometry(QtCore.QRect(580, 190, 331, 201))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_2 = QtWidgets.QLabel(parent=self.tab1)
        self.label_2.setGeometry(QtCore.QRect(720, 160, 60, 16))
        self.label_2.setObjectName("label_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=self.tab1)
        self.textBrowser_3.setGeometry(QtCore.QRect(1000, 50, 331, 201))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_3 = QtWidgets.QLabel(parent=self.tab1)
        self.label_3.setGeometry(QtCore.QRect(1130, 30, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.tab1)
        self.label_4.setGeometry(QtCore.QRect(1130, 280, 111, 16))
        self.label_4.setObjectName("label_4")
        self.textBrowser_4 = QtWidgets.QTextBrowser(parent=self.tab1)
        self.textBrowser_4.setGeometry(QtCore.QRect(1000, 300, 331, 201))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = StrangleTab()
        self.tab2.setObjectName("tab2")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = PositionTab()
        self.tabWidget.addTab(self.tab3, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnConnect.setText(_translate("MainWindow", "链接客户端"))
        self.inputPort.setText(_translate("MainWindow", "7497"))
        self.groupBox_2.setTitle(_translate("MainWindow", "定时任务"))
        self.label_17.setText(_translate("MainWindow", "下单任务"))
        self.btn_cancel_all_schedule.setText(_translate("MainWindow", "取消所有任务"))
        self.label_18.setText(_translate("MainWindow", "定时平仓"))
        self.label_schedule_open_summary.setText(_translate("MainWindow", "无"))
        self.label_schedule_close_summary.setText(_translate("MainWindow", "无"))
        self.btn_get_all_schedule.setText(_translate("MainWindow", "查看任务"))
        self.label_schedule_close_summary_2.setText(_translate("MainWindow", "无"))
        self.label_19.setText(_translate("MainWindow", "盈利平仓"))
        self.label_20.setText(_translate("MainWindow", "TWS"))
        self.label_22.setText(_translate("MainWindow", "模拟端口7497"))
        self.label_23.setText(_translate("MainWindow", "实盘端口7496"))
        self.label_24.setText(_translate("MainWindow", "实盘端口4001"))
        self.label_21.setText(_translate("MainWindow", "gate"))
        self.label_25.setText(_translate("MainWindow", "模拟端口4002"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. 进入global configure，打开settings</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.左侧选择API节点，打开settings</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. check 右侧enable activeX or Socket Client</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3.uncheck 右侧 read-only api，给与接口下单权限</p></body></html>"))
        self.label.setText(_translate("MainWindow", "设置方法"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. 下单后自动采用中间价且自动重试3次，每次采用最新中间价并向不利方向偏移0.015</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.勾选使用自定义价格后，不会偏移，只会多次使用该价格下单</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3.定时任务，可在首页查看任务，刷新查看</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4.盘后IB接口停止提供数据，则无法显示正常ask/bid ，iv等数据</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5.电脑自动sleep后，定时脚本无法正常运行</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "提示"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. 输入股票code后，确认获取股票报价，等待x秒后当前价格显示则成功</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.输入期权到期周数，并确定(等待较久)。下方期权到期日输入框更新则成功</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3.输入strike距离，并按回车获取strike，所有勾选使用的leg均需要获取</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4.点击刷新价格按钮，leg的iv，当前价格均自动更新则成功</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5.此时可以自动下单了</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">6.低于iv和下单差价暂未使用</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "下单操作顺序"))
        self.label_4.setText(_translate("MainWindow", "平仓操作顺序"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. 进入平仓信息页面，点击获取持仓。只能获取到程序下单成功的持仓</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.盈利/损失平仓百分比如0.2则代表20%</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3.盈利/损失自动平仓，每分钟会检查持仓状态，符合盈利损失条件则使用中间价平仓(同样重试3次)</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "连接客户端"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "策略信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("MainWindow", "平仓信息"))
from UIElements.PositionTab import PositionTab
from UIElements.StrangleTab import StrangleTab


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
